FROM node:18-buster

WORKDIR /app

COPY package.json package-lock.json ./
COPY websocket/package.json ./websocket/package.json

RUN npm install --workspace=websocket

COPY . .

RUN npm run prisma:generate
RUN npm run build --workspace=websocket

CMD ["npm", "run", "start", "--workspace=websocket"]
