FROM node:18-alpine

WORKDIR /app

COPY package.json package-lock.json ./
COPY website/package.json ./website/package.json
COPY website/package-lock.json ./website/package-lock.json

RUN npm install --workspace=website

COPY . .

RUN npm run prisma:generate
RUN npm run build --workspace=website

CMD ["npm", "run", "start", "--workspace=website"]
